version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gha-patching:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "all"
    groups:
      composer-patching:
        update-types:
          - "minor"
          - "patch"