# see http://about.travis-ci.org/docs/user/languages/php/ for more hints

language: php
dist: trusty
sudo: required

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

before_script:
  - git clone https://github.com/eustasy/normal-checks.git
  - mv normal-checks/.codeclimate.yml .codeclimate.yml
  - mv normal-checks/.stylelintrc.json .stylelintrc.json
  - mv normal-checks/.stylelintignore .stylelintignore

script:
  - ./normal-checks/css.sh
  - ./normal-checks/javascript.sh
  - ./normal-checks/php.sh
  - php normal-checks/json.php
  - php normal-checks/xml.php
# - php _tests/authenticatron.php

notifications:
  email:
    recipients:
      - lewisgoddard@eustasy.org
    on_success: change
    on_failure: always
